# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U3JUYSABxHp13m8b36NrKHlW_vc4qQtF
"""

age_text = input ('Enter your age: ')
age_number = int (age_text)
print (f'Your age is,  {age_number}')

