# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gug2ckwdMNCPX5kFWIhdZI_YWee6yTuf
"""

score = float (input('Enter your score: '))
if score >= 90:
  print ('Grade: A')
elif score >= 80:
  print ('Grade: B')
elif score >= 70:
  print ('Grade: C')
elif score >= 60:
  print ('Grade: D')
else:
  print ('Grade: F')