# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gug2ckwdMNCPX5kFWIhdZI_YWee6yTuf
"""

# Basics of Lists

scores = [56, 89, 99, 78, 67]
print(scores)

scores.append(49)
print(scores)

scores.remove(56)
print(scores)

scores.sort()
print(scores)

print('How many scores: ', len(scores))

