# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U3JUYSABxHp13m8b36NrKHlW_vc4qQtF
"""

user_name = input("Enter your name: ")
print (f'Welcome, {user_name}')

