# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gug2ckwdMNCPX5kFWIhdZI_YWee6yTuf
"""

# Print numbers 1–20 but only the ones divisible by 3
for i in range(1, 21):
  if i % 3 == 0:
    print(i)