# -*- coding: utf-8 -*-
"""GitHub.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xBNiTcsibc6lE0Mt0qyqTnXQk-Ne33ad
"""

# Reading from a text file using .strip command (line by line)

with open ('file.txt', 'r')  as f:
  for line in f:
    print(line.strip())

