# -*- coding: utf-8 -*-
"""GitHub.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xBNiTcsibc6lE0Mt0qyqTnXQk-Ne33ad
"""

# Reading from a csv file

import csv

with open ('student.csv', 'r', newline = '') as f:
  reader = csv.reader(f)

  for row in reader:
    print(row)

