# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gug2ckwdMNCPX5kFWIhdZI_YWee6yTuf
"""

model_config = {
    'learning_rate' : 0.01,
    'epochs' : 10,
    'batch_size' : 32
}
print ('Training for', model_config['epochs'], 'epochs')