# -*- coding: utf-8 -*-
"""GitHub.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xBNiTcsibc6lE0Mt0qyqTnXQk-Ne33ad
"""

# try/except basics

try:
  with open('missing.csv', 'r') as f:
    print(f.read())

except FileNotFoundError:
  print('File not found!')

