# -*- coding: utf-8 -*-
"""GitHub.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xBNiTcsibc6lE0Mt0qyqTnXQk-Ne33ad
"""

# Writing to a csv file

import csv

with open ('student.csv', 'w', newline = '') as f:
  writer = csv.writer(f)
  writer.writerow(['Name', 'Marks'])
  writer.writerow(['Zimal', 98])
  writer.writerow(['Sara', 78])
  writer.writerow(['Zumar', 82])
  writer.writerow(['Fajar', 94])
  writer.writerow(['Hooria', 86])

print('File written!')

