# -*- coding: utf-8 -*-
"""GitHub.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xBNiTcsibc6lE0Mt0qyqTnXQk-Ne33ad
"""

# Writing to a Text File

with open ('file.txt', 'w') as f:
  f.write("I'm Zimal. \n")
  f.write("I'm 19 years old. ")
print('File written!')

